TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += _NAME_.db
DATA += _NAME_.proto

#=======================================
include $(TOP)/configure/RULES
